### PR TITLE
Add Rescue, split parameters and the sponge struct, and sharing some components

### PR DESCRIPTION
**Pull request by weikengchen**
This PR is to the `experimental` repo.

It adds Rescue (untested) and separates the parameters from the sponge struct. 

More updates are incoming:
- tests with more decent parameters for one common curves
- more tests on Rescue

One thing that pops up during this change:
- Rescue and Poseidon share a lot of code in common---because they are merely different `permutation`, but the sponge structure is similar. We may extract more code from here.

### CODE REVIEW

**Comment by Will-Lin4** [comment]
You mentioned that the only difference between Rescue and Poseidon are their permutations. Do you see that the general structure will be similar for newer Sponges? Would it be worth just introducing a Permutation trait that we can simply swap out?

**Comment by weikengchen** [comment]
Good point. Reading Wikipedia, ideally (duplex) sponges would only differ in terms of the permutation function.

Let me cc @ValarDragon for some opinions. Basically, the implementations of Rescue and Poseidon share a lot of the code, and the only difference is in the permutations. So, we are thinking to structure the code in a way that avoids duplication. What do you think?

**Comment by Will-Lin4** [comment]
> Good point. Reading Wikipedia, ideally (duplex) sponges would only differ in terms of the permutation function.
> 
> Let me cc @ValarDragon for some opinions. Basically, the implementations of Rescue and Poseidon share a lot of the code, and the only difference is in the permutations. So, we are thinking to structure the code in a way that avoids duplication. What do you think?

Yes and possibly allow less effort for implementing similar Sponges with the same structure in the future.

**Comment by ValarDragon** [comment]
Sorry, somehow I missed this ping. I think the scaffolding we should do given our recent sponge conversations is to have a SpongeTrait, and then build out a trait where all you do is specify a permutation, and then it handles the rest

**Pull request closed without merging**
